### ISSUE TITLE
pdf document add on in products

### ISSUE THREAD

**Issue by BryanDouglass** [danderson421/MoneyMetrics#11]
Dwayne, 

In Dealerships, when you click into the products they offer, may we have an option to attach pdf rate sheets for the products.  

Please let me know if you have any questions. 

Thanks,

**Comment by danderson421** [comment]
Hi -
this functionality exists. once you've added a product to a dealership, you can open up that product (from the dealership interface) and add a document. When you add a document using this route, it's only associated with that instance of the product for that dealership.

you can also add documents to products that are associated with providers.
