### ISSUE TITLE
Icon for inheriting address

### ISSUE THREAD

**Issue by BryanDouglass** [danderson421/MoneyMetrics#32]
Regarding the physical and mailing address icon that you can click to inherit same as physical address, needs to be more obvious and spelled out I was told.

**Comment by danderson421** [comment]
when adding a contact to a client, the address, city, state and zip will autofill from the client record.

**Comment by danderson421** [comment]
After reviewing this issue, the icon is the same relative size as all the other icons in the application. There is a tooltip that pops up on hover with a descriptions of the buttons function. After learning how it works, a user will not have any difficulty using the button.
