### ISSUE TITLE
Unable to remove a contact

### ISSUE THREAD

**Issue by BryanDouglass** [danderson421/MoneyMetrics#41]
Sasan Sahili 

with Hyundai of new port richey, llc

**Comment by danderson421** [comment]
There are a few places where contacts can be deleted... can you tell me which interface you were using? Were you in the client interface, or did you go to all contacts.

**Comment by BryanDouglass** [comment]
I went into contacts, People, looked up the contact through An email address to make sure they were correct. When I tried to delete in that interface it would not delete.

Thanks,

___________________________________
Bryan D. Krejci
Dealership Support

[cid:]
(402) 999-3419 Cell
(813) 223-0085 x210 Phone
(866) 950-2672 Fax
BryanK@cn-group.com<mailto:BryanK@cn-group.com>  Email
http://www.cn-group.com<http://www.cn-group.com/> Website

Unless otherwise indicated or obvious from the nature of the transmittal, the information contained in this message is confidential information intended solely for the use of the addressee. If the reader of this message is not the intended recipient, or the employee or agent responsible to deliver it to the intended recipient, you are hereby notified that any dissemination, distribution or copying of this communication or any of the information in it is strictly prohibited. If you have received this communication in error, please advise the sender by reply e-mail and then delete the message.

**Comment by danderson421** [comment]
I deleted the contact from the Contacts interface without issue.

**Comment by BryanDouglass** [comment]
Dwayne,

Thanks, it now shows it being deleted and another one I tried earlier. It just didn’t do anything after I hit delete.

___________________________________
Bryan D. Krejci
Dealership Support

[cid:]
(402) 999-3419 Cell
(813) 223-0085 x210 Phone
(866) 950-2672 Fax
BryanK@cn-group.com<mailto:BryanK@cn-group.com>  Email
http://www.cn-group.com<http://www.cn-group.com/> Website

Unless otherwise indicated or obvious from the nature of the transmittal, the information contained in this message is confidential information intended solely for the use of the addressee. If the reader of this message is not the intended recipient, or the employee or agent responsible to deliver it to the intended recipient, you are hereby notified that any dissemination, distribution or copying of this communication or any of the information in it is strictly prohibited. If you have received this communication in error, please advise the sender by reply e-mail and then delete the message.

**Comment by danderson421** [comment]
I also deleted the contact using the steps you indicated. The interface prompts you to confirm you actually want to delete the record. This prompt could be suppressed based on your browser setting, or ancillary software products or plugins.

**Comment by BryanDouglass** [comment]
It did prompt me. Unlike the other MM’s that when you delete it will put you on a different page. So I thought it was not following through. Thank you for helping me out.

___________________________________
Bryan D. Krejci
Dealership Support

[cid:]
(402) 999-3419 Cell
(813) 223-0085 x210 Phone
(866) 950-2672 Fax
BryanK@cn-group.com<mailto:BryanK@cn-group.com>  Email
http://www.cn-group.com<http://www.cn-group.com/> Website

Unless otherwise indicated or obvious from the nature of the transmittal, the information contained in this message is confidential information intended solely for the use of the addressee. If the reader of this message is not the intended recipient, or the employee or agent responsible to deliver it to the intended recipient, you are hereby notified that any dissemination, distribution or copying of this communication or any of the information in it is strictly prohibited. If you have received this communication in error, please advise the sender by reply e-mail and then delete the message.
