### ISSUE TITLE
Inactive, Active Dealers

### ISSUE THREAD

**Issue by BryanDouglass** [danderson421/MoneyMetrics#55]
Dwayne, 

When you change the status to Inactive on the dealerships, it still shows on the dealership list. Example 'Grand Auto Sales'. On out MM Production we have in set to go to the inactive dealership list; we'd prefer it like that. Thanks Dwayne. Happy New Year

**Comment by danderson421** [comment]
the most likely solution is to provide an option, probably a checkbox, that would filter the list to only show active clients.

**Comment by danderson421** [comment]
added column filer to company table
